// Copyright 2017-2026 @pezkuwi/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/dev', path: 'auto', type: 'auto', version: '0.85.4' };
